apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-fedora
  name: vm-fedora
  namespace: vm-test
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-9-minimal-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:   
        kubevirt.io/vm: vm-fedora
    spec:
      domain:
        cpu:
          cores: 6      
        resources:
          requests:
            memory: 16384M
        devices:
          disks:
          - name: containerdisk
            disk: {}
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          # - name: eth0
          #   masquerade: {}
          - name: vm-network
            bridge: {}          
      networks:
      # - name: eth0
      #   pod: {}
      - name: vm-network
        multus:
          networkName: vm-guests/br1
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora 
              chpasswd: { expire: False }
          name: cloudinitdisk
          # cloudInitConfigDrive: 
          #   userData: |-
          #     #cloud-config
          #     user: alex
          #     password: fedora
          #     chpasswd: { expire: False }
      # accessCredentials:
      #   - sshPublicKey:
      #       propagationMethod:
      #         configDrive: {}
      #       source:
      #         secret:
      #           secretName: authorized-keys
                    