apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-fedora
    app: ibm-sterling    
  name: vm-fedora-a
  namespace: ibm-sterling
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:   
        kubevirt.io/vm: vm-fedora
        app: ibm-sterling        
    spec:
      affinity:
        podAntiAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution means the scheduler MUST satisfy this rule.
          # If it cannot find a node, the pod will remain in a Pending state.
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: ibm-sterling # Target pods that also have this label
              topologyKey: kubernetes.io/hostname # Ensure they are on different nodes    
      domain:
        cpu:
          cores: 6      
        resources:
          requests:
            memory: 16384M
        devices:
          disks:
          - name: containerdisk
            disk: {}
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          # - name: eth0
          #   masquerade: {}
          - name: vm-network
            bridge: {}          
      networks:
      # - name: eth0
      #   pod: {}
      - name: vm-network
        multus:
          networkName: ibm-sterling/br1
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/acmenezes/fedora-container-disk:latest
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora 
              chpasswd: { expire: False }
          name: cloudinitdisk
                    