---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fedora-overlay-router
  namespace: vm-guests
  labels:
    app: fedora-overlay-router
  annotations:
    docs.ocp-virt.io/category: "networking"
    docs.ocp-virt.io/complexity: "intermediate"
    docs.ocp-virt.io/description: "Service account for router pod with network privileges"

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: fedora-overlay-router-scc
  annotations:
    docs.ocp-virt.io/category: "networking"
    docs.ocp-virt.io/complexity: "intermediate"
    docs.ocp-virt.io/description: "SCC for router pod requiring network admin capabilities"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
groups: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fedora-overlay-router-role
  annotations:
    docs.ocp-virt.io/category: "networking"
    docs.ocp-virt.io/description: "Cluster role for router pod operations"
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - fedora-overlay-router-scc
    verbs:
      - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fedora-overlay-router-binding
  annotations:
    docs.ocp-virt.io/category: "networking"
    docs.ocp-virt.io/description: "Bind router service account to SCC"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fedora-overlay-router-role
subjects:
  - kind: ServiceAccount
    name: fedora-overlay-router
    namespace: vm-guests 