apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond
spec:
  desiredState:
    interfaces:
      - name: bond1 
        description: uplink to secondary network 
        type: bond
        state: up
        link-aggregation:
          mode: 802.3ad 
          options:
            primary: eno2np1 
          port: 
            - eno2np1
            - eno3np1