apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-localnet-vlan
  namespace: vm-guests
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovn-localnet-vlan",
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "vm-guests/ovn-localnet-vlan",
    "vlanID": 100,
    "subnets": "192.168.200.0/24",
    "excludeSubnets": "192.168.200.1/32"
  }' 