apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-localnet-static
  namespace: vm-guests
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovn-localnet-static",
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "vm-guests/ovn-localnet-static",
    "subnets": "192.168.100.0/24",
    "excludeSubnets": "192.168.100.1/32,192.168.100.100-192.168.100.200"
  }' 