apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  additionalNetworks:
  - name: physnet1
    namespace: openshift-multus
    rawCNIConfig: '{
      "cniVersion": "0.3.1",
      "name": "physnet1",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "openshift-multus/physnet1"
    }'
    type: Raw 