apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-localnet-custom-static
  namespace: vm-guests
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovn-localnet-custom-static",
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "vm-guests/ovn-localnet-custom-static",
    "subnets": "YOUR_NETWORK_RANGE/CIDR",
    "excludeSubnets": "GATEWAY_IP/32,RESERVED_RANGE_START-RESERVED_RANGE_END"
  }'

# Example configurations:
#
# For 10.0.0.0/24 network with gateway 10.0.0.1:
# "subnets": "10.0.0.0/24",
# "excludeSubnets": "10.0.0.1/32,10.0.0.200-10.0.0.254"
#
# For 172.16.1.0/24 network with multiple exclusions:
# "subnets": "172.16.1.0/24", 
# "excludeSubnets": "172.16.1.1/32,172.16.1.10-172.16.1.20,172.16.1.100-172.16.1.110"
#
# For larger subnet 192.168.0.0/16 with VM range:
# "subnets": "192.168.0.0/16",
# "excludeSubnets": "192.168.0.1/32,192.168.0.0/24,192.168.255.0/24" 