apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: lvm-storage
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - lvmcluster.yaml
  - storage-class.yaml

namespace: openshift-storage 