apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-ovn-overlay-2
  namespace: vm-guests
  labels:
    kubevirt.io/vm: fedora-ovn-overlay-2
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-ovn-overlay-2
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4096M
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: ovn-net
              bridge: {}
      networks:
        - name: ovn-net
          multus:
            networkName: vm-guests/ovn-overlay-static
      volumes:
        - dataVolume:
            name: fedora-overlay-volume-2
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk
  dataVolumeTemplates:
    - metadata:
        name: fedora-overlay-volume-2
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 33Gi
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images 