apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools: 
  - name: vm-storage
    path: "/tmp/hostdata" 
# workload:
#   nodeSelector:
#     kubernetes.io/os: linux