apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-overlay-layer3
  namespace: vm-guests
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovn-overlay-layer3",
    "type": "ovn-k8s-cni-overlay",
    "topology": "layer3",
    "netAttachDefName": "vm-guests/ovn-overlay-layer3",
    "subnets": "10.100.0.0/16",
    "excludeSubnets": "10.100.0.1/32",
    "role": "primary"
  }' 