apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-overlay-dhcp
  namespace: vm-guests
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovn-overlay-dhcp",
    "type": "ovn-k8s-cni-overlay",
    "topology": "layer2",
    "netAttachDefName": "vm-guests/ovn-overlay-dhcp"
  }' 