apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-overlay-static
  namespace: vm-guests
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovn-overlay-static",
    "type": "ovn-k8s-cni-overlay",
    "topology": "layer2",
    "netAttachDefName": "vm-guests/ovn-overlay-static",
    "subnets": "10.200.0.0/16",
    "excludeSubnets": "10.200.0.1/32"
  }' 