apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: lvm-operator
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - operator-group.yaml
  - subscription.yaml

namespace: openshift-storage 