# This file ensures the troubleshooting directory is committed to Git
# Remove this file when adding actual troubleshooting script configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: placeholder-troubleshooting-scripts
  annotations:
    docs.ocp-virt.io/category: "scripts"
    docs.ocp-virt.io/complexity: "intermediate"
    docs.ocp-virt.io/environment: "cloud,bare-metal,hybrid"
    docs.ocp-virt.io/description: "Placeholder for troubleshooting script configurations"
    docs.ocp-virt.io/prerequisites: "bash,openshift-cli,kubectl"
    docs.ocp-virt.io/use-cases: "debugging,diagnostics,log-collection"
data:
  readme: |
    This directory will contain troubleshooting scripts including:
    - VM debugging scripts
    - Network connectivity tests
    - Storage diagnostic tools
    - Log collection utilities 