apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ocp-virt-base
  annotations:
    docs.ocp-virt.io/category: "platform"
    docs.ocp-virt.io/complexity: "intermediate"
    docs.ocp-virt.io/environment: "cloud,bare-metal,hybrid"
    docs.ocp-virt.io/description: "Base OpenShift Virtualization platform configuration"
    docs.ocp-virt.io/prerequisites: "openshift-cluster,cluster-admin"
    docs.ocp-virt.io/use-cases: "virtualization,containers,hybrid-workloads"

# Base resources - core platform components
resources:
  # Namespaces
  - ../../base/namespaces/vm-guests-namespace.yaml
  
  # Network base components
  - ../../base/network/overlay/ovn-k8s-overlay-nad-static-cloud.yaml
  - ../../base/network/overlay/ovn-k8s-overlay-nad-dhcp-cloud.yaml
  - ../../base/network/overlay/ovn-k8s-overlay-nad-layer3-cloud.yaml

# Optional components that can be included via overlays
components:
  # Uncomment based on environment needs
  # - components/localnet-networking
  # - components/sr-iov-networking
  # - components/ceph-storage
  # - components/monitoring
  # - components/backup

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/part-of: ocp-virt-platform
  app.kubernetes.io/managed-by: kustomize

# Common annotations for RAG optimization
commonAnnotations:
  docs.ocp-virt.io/version: "v1.0.0"
  docs.ocp-virt.io/maintainer: "ocp-virt-reference"

# Images - centralized image management
images:
  # Example: Override CNV operator images if needed
  # - name: registry.redhat.io/container-native-virtualization/virtio-win
  #   newTag: "latest"

# Namespace where resources will be created (can be overridden)
namespace: vm-guests

# Patches that can be applied to resources
patches:
  # Example: Resource limit patches
  # - target:
  #     kind: VirtualMachine
  #   patch: |-
  #     - op: replace
  #       path: /spec/template/spec/domain/memory/guest
  #       value: "8Gi"

# Replacements for environment-specific values
replacements:
  # Example: Replace subnet ranges based on environment
  # - source:
  #     kind: ConfigMap
  #     name: network-config
  #     fieldPath: data.subnet
  #   targets:
  #   - select:
  #       kind: NetworkAttachmentDefinition
  #     fieldPaths:
  #     - spec.config.subnets 