# This file ensures the production directory is committed to Git
# Remove this file when adding actual Ansible inventory configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: placeholder-production-inventory
  annotations:
    docs.ocp-virt.io/category: "automation"
    docs.ocp-virt.io/complexity: "advanced"
    docs.ocp-virt.io/environment: "production"
    docs.ocp-virt.io/description: "Placeholder for production environment Ansible inventory"
    docs.ocp-virt.io/prerequisites: "ansible,production-cluster"
    docs.ocp-virt.io/use-cases: "production-automation,enterprise-deployment"
data:
  readme: |
    This directory will contain production environment inventory including:
    - hosts.yml - Production cluster hosts
    - group_vars/ - Production-specific variables
    - host_vars/ - Host-specific configurations
    - High-availability and security settings 